github_url: https://github.com/Polidea/RxBluetoothKit
module: RxBluetoothKit
author_url: https://polidea.com
author: Polidea
swift_version: 4.1.2
clean: true
output: ./generated
root-url: https://polidea.github.io/RxBluetoothKit/

podspec: ../RxBluetoothKit.podspec
